### ISSUE TITLE
Draw ready check on party list incorrect.

### ISSUE THREAD

**Issue by Brasolis** [Infiziert90/ReadyCheckHelper#1]
Not sure when it started but the overlay for drawing the ready check marks on the party list isn't marking people correctly. Seems to randomly assign markers to people. Sometimes it shows 8/8 ready marks before the check is even done, sometimes it simple attributes readys to people who aren't. The chat output is correct on who is/isn't ready however.

My party list has default sorting if that makes a difference.

**Comment by Brasolis** [comment]
Here is an example where I initiate the ready check and it attributes my ready to the RDM, and then all the readys from there are incorrect.

https://i.imgur.com/yZkziBf.mp4

**Comment by SayuShira** [comment]
It also shows for people that ain't there. This was after the ready check was done 4/4:

![image](https://github.com/Infiziert90/ReadyCheckHelper/assets/104025906/b92bbded-92ec-4df8-bf60-1d5a71bf66aa)

**Comment by Infiziert90** [comment]
This should be fixed now, if it still occurs please open a new issue
