### ISSUE TITLE
Icons mismatched when in non-A alliance

### ISSUE THREAD

**Issue by Cloud7050** [Infiziert90/ReadyCheckHelper#2]
When using readycheck in an alliance and opening the game's popup window, the game will display your party on the very left, then the other parties to its right. For example, if you are in party B, then the window will display parties in the order B-A-C. However, the plugin (always?) assumes parties to be in the order A-B-C, and thus overlays the tick/cross icons in that order incorrectly.

**Comment by Infiziert90** [comment]
This should be fixed in the new update, if it still occurs please open a new issue
